mod add_browser;
mod app_settings;
mod automation;
mod devices;
mod favorites_panel;
mod inspector;
mod instrument_menu;
mod macro_panel;
mod mixer;
mod modulator;
mod param_pick;
mod note_preview;
mod pattern_rack;
mod pattern_row_editor;
mod pattern_strip;
mod performance;
mod clip_variations;
mod piano_roll;
mod playlist;
mod project_browser;
mod settings;
mod shortcuts;
mod theme;
mod timeline;
mod track_rename;
mod transport;

pub use add_browser::{AddBrowserAction, AddBrowserUi, BrowserTab};
pub use app_settings::AppSettings;
pub use instrument_menu::{choice_to_instrument, track_name_for_choice};
pub use devices::DevicesUi;
pub use inspector::show_inspector;
pub use mixer::{MixerPanelResize, MixerUi, MIXER_PANEL_ID, MIXER_PANEL_MIN_HEIGHT};
pub use performance::PerformanceUi;
pub use pattern_rack::{PatternRackAction, PatternRackUi};
pub use pattern_row_editor::{PatternRowEditorAction, PatternRowEditorUi};
pub use piano_roll::PianoRollUi;
pub use playlist::{AudioImportRequest, PlaylistUi, PluginEditorRequest};
pub use project_browser::{ProjectBrowserAction, ProjectBrowserUi};
pub use settings::{SettingsAction, SettingsUi};
pub use shortcuts::{Action, Chord, PollFilter, SETTINGS_FILE};
pub use track_rename::{PatternLaneRenameUi, TrackRenameUi};
pub use transport::TransportUi;
