mod add_browser;
mod app_settings;
mod automation;
mod devices;
mod inspector;
mod instrument_menu;
mod mixer;
mod modulator;
mod performance;
mod piano_roll;
mod playlist;
mod project_browser;
mod settings;
mod shortcuts;
mod theme;
mod timeline;
mod transport;

pub use add_browser::{AddBrowserAction, AddBrowserUi, BrowserTab};
pub use app_settings::AppSettings;
pub use instrument_menu::{choice_to_instrument, track_name_for_choice};
pub use devices::{DevicesUi, DEVICES_STRIP_HEIGHT};
pub use inspector::show_inspector;
pub use mixer::MixerUi;
pub use performance::PerformanceUi;
pub use piano_roll::PianoRollUi;
pub use playlist::{AudioImportRequest, PlaylistUi, PluginEditorRequest};
pub use project_browser::{ProjectBrowserAction, ProjectBrowserUi};
pub use settings::{SettingsAction, SettingsUi};
pub use shortcuts::{Action, Chord, PollFilter, SETTINGS_FILE};
pub use transport::TransportUi;
